export const ONBOARDING = {
  POST_REQUEST: 'POST_ONBOARDING_REQUEST',
  POST_SUCCESS: 'POST_ONBOARDING_SUCCESS',
  POST_FAILED: 'POST_ONBOARDING_FAILED',
  GET_REQUEST: 'GET_ONBOARDING_REQUEST',
  GET_SUCCESS: 'GET_ONBOARDING_SUCCESS',
  GET_FAILED: 'GET_ONBOARDING_FAILED',
  DELET_REQUEST: 'DELET_ONBOARDING_REQUEST',
  DELET_SUCCESS: 'DELET_ONBOARDING_SUCCESS',
  DELET_FAILED: 'DELET_ONBOARDING_FAILED'
}
